### ISSUE TITLE
compatibility with gitbucket 4.10

### ISSUE THREAD

**Issue by McFoggy** [asciidoctor/gitbucket-asciidoctor-plugin#13]
Please consider to adapt to gitbucket 4.10, see [release notes](https://gitbucket.github.io/gitbucket-news/gitbucket/2017/02/25/gitbucket-4.10.html)

**Comment by lefou** [comment]
Interesting, version 1.0.1 built for gitbucket 4.0 works also with 4.10.

**Comment by lefou** [comment]
I just release version 1.0.2 which is explicitly compatible with gitbucket 4.10.
