### ISSUE TITLE
Plugin version is 1.0.2, but database version is 0.1

### ISSUE THREAD

**Issue by rockccf** [asciidoctor/gitbucket-asciidoctor-plugin#17]
I am using gitbucket 4.21.2 and I got the following error message.
Error during plugin initialization: gitbucket-4.10-asciidoctor-plugin-assembly-1.0.2.jar
java.lang.IllegalStateException: Plugin version is 1.0.2, but database version is 0.1

Any solutions?

**Comment by lefou** [comment]
Have you upgraded from a very early version of the plugin? Have you tried uninstalling the old version, before installing the new one? 

Besides, asciidoctor-plugin stores nothing in the database and has no need for any database migration after an update. If the above hint does not help, you could try if you can delete any old version information of this plugin in your installation.

**Comment by rockccf** [comment]
Thanks. I deleted the old version info from the DB and it works.
