### ISSUE TITLE
The plugin is not working anymore for latest GitBucket versions

### ISSUE THREAD

**Issue by source-c** [asciidoctor/gitbucket-asciidoctor-plugin#21]
Subj.

GITBUCKET_VERSION | 4.32.0

Will be very nice to have this plug-in up-n-running again.

**Comment by lefou** [comment]
Fixed by https://github.com/asciidoctor/gitbucket-asciidoctor-plugin/pull/20.

**Comment by source-c** [comment]
Well done! Thank you very much.
